export const NOTIFICATION_TCP_CLIENT = Symbol('NOTIFICATION_TCP_CLIENT');
export const NOTIFICATION_RPC_GATEWAY = Symbol('NOTIFICATION_RPC_GATEWAY');
export const NOTIFICATION_SESSION_AUTHENTICATOR = Symbol(
  'NOTIFICATION_SESSION_AUTHENTICATOR',
);
