export const PAYMENT_TCP_CLIENT = Symbol('PAYMENT_TCP_CLIENT');
export const PAYMENT_RPC_GATEWAY = Symbol('PAYMENT_RPC_GATEWAY');
export const PAYMENT_SESSION_AUTHENTICATOR = Symbol(
  'PAYMENT_SESSION_AUTHENTICATOR',
);
