export const PROMOTION_RPC_GATEWAY = Symbol('PROMOTION_RPC_GATEWAY');
export const PROMOTION_TCP_CLIENT = Symbol('PROMOTION_TCP_CLIENT');
export const PROMOTION_SESSION_AUTHENTICATOR = Symbol(
  'PROMOTION_SESSION_AUTHENTICATOR',
);
