import 'dotenv/config';
import { drizzle } from 'drizzle-orm/node-postgres';
import { nutritionFoods } from '../../module/nutrition/domain/nutrition.schema';

const db = drizzle(process.env.DATABASE_URL!);

const foods: (typeof nutritionFoods.$inferInsert)[] = [
  {
    nameVi: 'ức gà',
    nameEn: 'chicken breast',
    aliases: ['uc ga', 'chicken breast'],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 120,
    protein100g: 22.5,
    carbs100g: 0,
    fat100g: 2.6,
  },
  {
    nameVi: 'đùi gà',
    nameEn: 'chicken thigh',
    aliases: ['dui ga', 'chicken thigh'],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 177,
    protein100g: 18.2,
    carbs100g: 0,
    fat100g: 11.2,
  },
  {
    nameVi: 'thịt bò nạc',
    nameEn: 'lean beef',
    aliases: ['thit bo nac', 'beef'],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 170,
    protein100g: 21,
    carbs100g: 0,
    fat100g: 9,
  },
  {
    nameVi: 'thịt heo nạc',
    nameEn: 'lean pork',
    aliases: ['thit heo nac', 'thit lon nac', 'pork', 'lean pork'],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 143,
    protein100g: 21,
    carbs100g: 0,
    fat100g: 6,
  },
  {
    nameVi: 'ba chỉ heo',
    nameEn: 'pork belly',
    aliases: [
      'ba chi heo',
      'ba roi heo',
      'thit ba chi',
      'thit ba roi',
      'thit lon ba chi',
      'thit lon ba roi',
      'thit heo ba chi',
      'pork belly',
    ],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 518,
    protein100g: 9.3,
    carbs100g: 0,
    fat100g: 53,
  },
  {
    nameVi: 'nạc vai heo',
    nameEn: 'pork shoulder',
    aliases: [
      'nac vai',
      'nac vai heo',
      'nac vai lon',
      'thit vai',
      'thit vai heo',
      'thit vai xay',
      'thit vai bam',
      'pork shoulder',
      'ground pork shoulder',
    ],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 242,
    protein100g: 17,
    carbs100g: 0,
    fat100g: 19,
  },
  {
    nameVi: 'nạc dăm heo',
    nameEn: 'pork collar',
    aliases: [
      'nac dam',
      'nac dam heo',
      'nac dam lon',
      'thit nac dam',
      'thit heo nac dam',
      'pork collar',
      'pork butt',
    ],
    category: 'meat',
    state: 'raw' as const,
    calories100g: 260,
    protein100g: 17,
    carbs100g: 0,
    fat100g: 21,
  },
  {
    nameVi: 'trứng gà',
    nameEn: 'chicken egg',
    aliases: ['trung ga', 'egg'],
    category: 'protein',
    state: 'raw' as const,
    calories100g: 143,
    protein100g: 12.6,
    carbs100g: 0.7,
    fat100g: 9.5,
  },
  {
    nameVi: 'cơm trắng',
    nameEn: 'cooked white rice',
    aliases: ['com trang', 'rice', 'white rice'],
    category: 'grain',
    state: 'cooked' as const,
    calories100g: 130,
    protein100g: 2.4,
    carbs100g: 28.2,
    fat100g: 0.3,
  },
  {
    nameVi: 'gạo trắng',
    nameEn: 'raw white rice',
    aliases: ['gao trang', 'uncooked rice'],
    category: 'grain',
    state: 'raw' as const,
    calories100g: 365,
    protein100g: 7.1,
    carbs100g: 80,
    fat100g: 0.7,
  },
  {
    nameVi: 'bún',
    nameEn: 'rice vermicelli',
    aliases: ['bun', 'bun tuoi', 'rice noodles', 'fresh rice vermicelli'],
    category: 'grain',
    state: 'cooked' as const,
    calories100g: 109,
    protein100g: 1.8,
    carbs100g: 25,
    fat100g: 0.2,
  },
  {
    nameVi: 'phở',
    nameEn: 'pho noodles',
    aliases: ['pho', 'rice noodle'],
    category: 'grain',
    state: 'cooked' as const,
    calories100g: 115,
    protein100g: 2,
    carbs100g: 26,
    fat100g: 0.2,
  },
  {
    nameVi: 'mì spaghetti',
    nameEn: 'cooked spaghetti',
    aliases: ['mi spaghetti', 'spaghetti'],
    category: 'grain',
    state: 'cooked' as const,
    calories100g: 158,
    protein100g: 5.8,
    carbs100g: 30.9,
    fat100g: 0.9,
  },
  {
    nameVi: 'bánh mì',
    nameEn: 'baguette',
    aliases: ['banh mi', 'bread'],
    category: 'grain',
    state: 'unknown' as const,
    calories100g: 270,
    protein100g: 8,
    carbs100g: 55,
    fat100g: 3.2,
  },
  {
    nameVi: 'khoai tây',
    nameEn: 'potato',
    aliases: ['khoai tay', 'potato'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 77,
    protein100g: 2,
    carbs100g: 17,
    fat100g: 0.1,
  },
  {
    nameVi: 'khoai lang',
    nameEn: 'sweet potato',
    aliases: ['khoai lang', 'sweet potato'],
    category: 'vegetable',
    state: 'cooked' as const,
    calories100g: 90,
    protein100g: 2,
    carbs100g: 20.7,
    fat100g: 0.2,
  },
  {
    nameVi: 'bắp cải',
    nameEn: 'cabbage',
    aliases: ['bap cai', 'cabbage'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 25,
    protein100g: 1.3,
    carbs100g: 5.8,
    fat100g: 0.1,
  },
  {
    nameVi: 'xà lách',
    nameEn: 'lettuce',
    aliases: ['xa lach', 'lettuce', 'rau xalach'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 15,
    protein100g: 1.4,
    carbs100g: 2.9,
    fat100g: 0.2,
  },
  {
    nameVi: 'rau thơm',
    nameEn: 'mixed Vietnamese herbs',
    aliases: [
      'rau thom',
      'rau song',
      'rau an kem',
      'herbs',
      'vietnamese herbs',
      'mixed herbs',
    ],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 30,
    protein100g: 2.5,
    carbs100g: 5,
    fat100g: 0.6,
    fiber100g: 3,
  },
  {
    nameVi: 'tía tô',
    nameEn: 'perilla leaf',
    aliases: ['tia to', 'la tia to', 'perilla', 'perilla leaf'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 37,
    protein100g: 3.9,
    carbs100g: 7,
    fat100g: 1,
    fiber100g: 6,
  },
  {
    nameVi: 'kinh giới',
    nameEn: 'Vietnamese balm',
    aliases: ['kinh gioi', 'vietnamese balm', 'elsholtzia'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 32,
    protein100g: 2.8,
    carbs100g: 5.8,
    fat100g: 0.7,
    fiber100g: 4,
  },
  {
    nameVi: 'mùi tàu',
    nameEn: 'culantro',
    aliases: ['mui tau', 'mui tau', 'ngo gai', 'culantro'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 23,
    protein100g: 2,
    carbs100g: 4,
    fat100g: 0.5,
    fiber100g: 3,
  },
  {
    nameVi: 'húng láng',
    nameEn: 'Vietnamese basil',
    aliases: ['hung lang', 'hung que', 'basil', 'vietnamese basil'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 23,
    protein100g: 3.2,
    carbs100g: 2.7,
    fat100g: 0.6,
    fiber100g: 1.6,
  },
  {
    nameVi: 'cà chua',
    nameEn: 'tomato',
    aliases: ['ca chua', 'tomato'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 18,
    protein100g: 0.9,
    carbs100g: 3.9,
    fat100g: 0.2,
  },
  {
    nameVi: 'dưa leo',
    nameEn: 'cucumber',
    aliases: ['dua leo', 'cucumber'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 15,
    protein100g: 0.7,
    carbs100g: 3.6,
    fat100g: 0.1,
  },
  {
    nameVi: 'cà rốt',
    nameEn: 'carrot',
    aliases: ['ca rot', 'carrot'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 41,
    protein100g: 0.9,
    carbs100g: 9.6,
    fat100g: 0.2,
  },
  {
    nameVi: 'đu đủ xanh',
    nameEn: 'green papaya',
    aliases: ['du du xanh', 'du du', 'green papaya', 'unripe papaya'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 43,
    protein100g: 0.5,
    carbs100g: 10.8,
    fat100g: 0.3,
    fiber100g: 1.7,
    sugar100g: 7.8,
  },
  {
    nameVi: 'hành tây',
    nameEn: 'onion',
    aliases: ['hanh tay', 'onion'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 40,
    protein100g: 1.1,
    carbs100g: 9.3,
    fat100g: 0.1,
  },
  {
    nameVi: 'hành tím',
    nameEn: 'shallot',
    aliases: [
      'hanh tim',
      'hanh kho',
      'cu hanh tim',
      'cu hanh kho',
      'shallot',
    ],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 72,
    protein100g: 2.5,
    carbs100g: 16.8,
    fat100g: 0.1,
  },
  {
    nameVi: 'tỏi',
    nameEn: 'garlic',
    aliases: ['toi', 'garlic'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 149,
    protein100g: 6.4,
    carbs100g: 33,
    fat100g: 0.5,
  },
  {
    nameVi: 'rau muống',
    nameEn: 'water spinach',
    aliases: ['rau muong', 'water spinach'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 19,
    protein100g: 2.6,
    carbs100g: 3.1,
    fat100g: 0.2,
  },
  {
    nameVi: 'cải thìa',
    nameEn: 'bok choy',
    aliases: ['cai thia', 'bok choy'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 13,
    protein100g: 1.5,
    carbs100g: 2.2,
    fat100g: 0.2,
  },
  {
    nameVi: 'đậu hũ',
    nameEn: 'tofu',
    aliases: ['dau hu', 'tofu'],
    category: 'protein',
    state: 'unknown' as const,
    calories100g: 76,
    protein100g: 8,
    carbs100g: 1.9,
    fat100g: 4.8,
  },
  {
    nameVi: 'đậu xanh',
    nameEn: 'mung bean',
    aliases: ['dau xanh', 'mung bean'],
    category: 'legume',
    state: 'raw' as const,
    calories100g: 347,
    protein100g: 23.9,
    carbs100g: 62.6,
    fat100g: 1.2,
  },
  {
    nameVi: 'đậu phộng',
    nameEn: 'peanut',
    aliases: ['dau phong', 'peanut'],
    category: 'nut',
    state: 'raw' as const,
    calories100g: 567,
    protein100g: 25.8,
    carbs100g: 16.1,
    fat100g: 49.2,
  },
  {
    nameVi: 'dầu ăn',
    nameEn: 'vegetable oil',
    aliases: ['dau an', 'vegetable oil', 'oil'],
    category: 'fat',
    state: 'unknown' as const,
    calories100g: 884,
    protein100g: 0,
    carbs100g: 0,
    fat100g: 100,
  },
  {
    nameVi: 'dầu olive',
    nameEn: 'olive oil',
    aliases: ['dau olive', 'olive oil'],
    category: 'fat',
    state: 'unknown' as const,
    calories100g: 884,
    protein100g: 0,
    carbs100g: 0,
    fat100g: 100,
  },
  {
    nameVi: 'đường',
    nameEn: 'sugar',
    aliases: ['duong', 'duong trang', 'sugar', 'white sugar'],
    category: 'seasoning',
    state: 'unknown' as const,
    calories100g: 387,
    protein100g: 0,
    carbs100g: 100,
    fat100g: 0,
  },
  {
    nameVi: 'muối',
    nameEn: 'salt',
    aliases: ['muoi', 'salt'],
    category: 'seasoning',
    state: 'unknown' as const,
    calories100g: 0,
    protein100g: 0,
    carbs100g: 0,
    fat100g: 0,
    sodium100g: 38758,
  },
  {
    nameVi: 'bột ngọt',
    nameEn: 'monosodium glutamate',
    aliases: ['bot ngot', 'mi chinh', 'msg', 'monosodium glutamate'],
    category: 'seasoning',
    state: 'unknown' as const,
    calories100g: 0,
    protein100g: 0,
    carbs100g: 0,
    fat100g: 0,
    sodium100g: 12300,
  },
  {
    nameVi: 'nước mắm',
    nameEn: 'fish sauce',
    aliases: ['nuoc mam', 'mam', 'fish sauce'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 35,
    protein100g: 5,
    carbs100g: 3.6,
    fat100g: 0,
    sodium100g: 7500,
  },
  {
    nameVi: 'giấm',
    nameEn: 'vinegar',
    aliases: ['giam', 'dam', 'giam tao', 'dam tao', 'vinegar', 'apple cider vinegar'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 18,
    protein100g: 0,
    carbs100g: 0.9,
    fat100g: 0,
    sodium100g: 5,
  },
  {
    nameVi: 'mật ong',
    nameEn: 'honey',
    aliases: ['mat ong', 'honey'],
    category: 'seasoning',
    state: 'unknown' as const,
    calories100g: 304,
    protein100g: 0.3,
    carbs100g: 82.4,
    fat100g: 0,
    sugar100g: 82.1,
  },
  {
    nameVi: 'dầu hào',
    nameEn: 'oyster sauce',
    aliases: ['dau hao', 'oyster sauce'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 51,
    protein100g: 1.4,
    carbs100g: 10.9,
    fat100g: 0.3,
    sodium100g: 2733,
  },
  {
    nameVi: 'nước màu',
    nameEn: 'caramel cooking sauce',
    aliases: [
      'nuoc mau',
      'nuoc hang',
      'keo dang',
      'caramel sauce',
      'caramel cooking sauce',
    ],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 290,
    protein100g: 0,
    carbs100g: 72,
    fat100g: 0,
    sugar100g: 70,
  },
  {
    nameVi: 'nước tương',
    nameEn: 'soy sauce',
    aliases: ['nuoc tuong', 'soy sauce'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 53,
    protein100g: 8.1,
    carbs100g: 4.9,
    fat100g: 0.6,
    sodium100g: 5493,
  },
  {
    nameVi: 'sốt teriyaki',
    nameEn: 'teriyaki sauce',
    aliases: ['sot teriyaki', 'teriyaki'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 89,
    protein100g: 5.9,
    carbs100g: 15.6,
    fat100g: 0,
  },
  {
    nameVi: 'sốt mayonnaise',
    nameEn: 'mayonnaise',
    aliases: ['mayonnaise', 'mayo'],
    category: 'sauce',
    state: 'unknown' as const,
    calories100g: 680,
    protein100g: 1,
    carbs100g: 0.6,
    fat100g: 75,
  },
  {
    nameVi: 'sữa tươi',
    nameEn: 'milk',
    aliases: ['sua tuoi', 'milk'],
    category: 'dairy',
    state: 'unknown' as const,
    calories100g: 61,
    protein100g: 3.2,
    carbs100g: 4.8,
    fat100g: 3.3,
  },
  {
    nameVi: 'phô mai',
    nameEn: 'cheese',
    aliases: ['pho mai', 'cheese'],
    category: 'dairy',
    state: 'unknown' as const,
    calories100g: 402,
    protein100g: 25,
    carbs100g: 1.3,
    fat100g: 33,
  },
  {
    nameVi: 'tôm',
    nameEn: 'shrimp',
    aliases: ['tom', 'shrimp'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 85,
    protein100g: 20,
    carbs100g: 0.2,
    fat100g: 0.5,
  },
  {
    nameVi: 'cá hồi',
    nameEn: 'salmon',
    aliases: ['ca hoi', 'salmon'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 208,
    protein100g: 20,
    carbs100g: 0,
    fat100g: 13,
  },
  {
    nameVi: 'cá basa',
    nameEn: 'basa fish',
    aliases: ['ca basa', 'basa'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 90,
    protein100g: 16,
    carbs100g: 0,
    fat100g: 3,
  },
  {
    nameVi: 'mực',
    nameEn: 'squid',
    aliases: ['muc', 'squid'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 92,
    protein100g: 15.6,
    carbs100g: 3.1,
    fat100g: 1.4,
  },
  {
    nameVi: 'cua',
    nameEn: 'crab',
    aliases: ['cua', 'crab'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 97,
    protein100g: 19.4,
    carbs100g: 0,
    fat100g: 1.5,
  },
  {
    nameVi: 'nghêu',
    nameEn: 'clam',
    aliases: ['ngheu', 'clam'],
    category: 'seafood',
    state: 'raw' as const,
    calories100g: 86,
    protein100g: 14.7,
    carbs100g: 3.6,
    fat100g: 1,
  },
  {
    nameVi: 'nấm',
    nameEn: 'mushroom',
    aliases: ['nam', 'mushroom'],
    category: 'vegetable',
    state: 'raw' as const,
    calories100g: 22,
    protein100g: 3.1,
    carbs100g: 3.3,
    fat100g: 0.3,
  },
  {
    nameVi: 'gạo lứt',
    nameEn: 'raw brown rice',
    aliases: ['gao lut', 'brown rice raw'],
    category: 'grain',
    state: 'raw' as const,
    calories100g: 370,
    protein100g: 7.9,
    carbs100g: 77,
    fat100g: 2.9,
  },
  {
    nameVi: 'cơm gạo lứt',
    nameEn: 'cooked brown rice',
    aliases: ['com gao lut', 'brown rice'],
    category: 'grain',
    state: 'cooked' as const,
    calories100g: 112,
    protein100g: 2.3,
    carbs100g: 23.5,
    fat100g: 0.8,
  },
  {
    nameVi: 'yến mạch',
    nameEn: 'oats',
    aliases: ['yen mach', 'oats'],
    category: 'grain',
    state: 'raw' as const,
    calories100g: 389,
    protein100g: 16.9,
    carbs100g: 66.3,
    fat100g: 6.9,
  },
  {
    nameVi: 'sữa chua',
    nameEn: 'yogurt',
    aliases: ['sua chua', 'yogurt'],
    category: 'dairy',
    state: 'unknown' as const,
    calories100g: 61,
    protein100g: 3.5,
    carbs100g: 4.7,
    fat100g: 3.3,
  },
  {
    nameVi: 'chuối',
    nameEn: 'banana',
    aliases: ['chuoi', 'banana'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 89,
    protein100g: 1.1,
    carbs100g: 22.8,
    fat100g: 0.3,
  },
  {
    nameVi: 'táo',
    nameEn: 'apple',
    aliases: ['tao', 'apple'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 52,
    protein100g: 0.3,
    carbs100g: 13.8,
    fat100g: 0.2,
  },
  {
    nameVi: 'bơ',
    nameEn: 'avocado',
    aliases: ['bo', 'avocado'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 160,
    protein100g: 2,
    carbs100g: 8.5,
    fat100g: 14.7,
  },
  {
    nameVi: 'xoài',
    nameEn: 'mango',
    aliases: ['xoai', 'mango'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 60,
    protein100g: 0.8,
    carbs100g: 15,
    fat100g: 0.4,
  },
  {
    nameVi: 'cam',
    nameEn: 'orange',
    aliases: ['cam', 'orange'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 47,
    protein100g: 0.9,
    carbs100g: 11.8,
    fat100g: 0.1,
  },
  {
    nameVi: 'chanh',
    nameEn: 'lime',
    aliases: ['chanh', 'lime', 'lemon'],
    category: 'fruit',
    state: 'raw' as const,
    calories100g: 30,
    protein100g: 0.7,
    carbs100g: 10.5,
    fat100g: 0.2,
  },
  {
    nameVi: 'ớt',
    nameEn: 'chili',
    aliases: ['ot', 'chili'],
    category: 'seasoning',
    state: 'raw' as const,
    calories100g: 40,
    protein100g: 1.9,
    carbs100g: 8.8,
    fat100g: 0.4,
  },
  {
    nameVi: 'tiêu',
    nameEn: 'black pepper',
    aliases: ['tieu', 'pepper'],
    category: 'seasoning',
    state: 'unknown' as const,
    calories100g: 251,
    protein100g: 10.4,
    carbs100g: 63.9,
    fat100g: 3.3,
  },
  {
    nameVi: 'bột mì',
    nameEn: 'wheat flour',
    aliases: ['bot mi', 'flour'],
    category: 'grain',
    state: 'raw' as const,
    calories100g: 364,
    protein100g: 10.3,
    carbs100g: 76.3,
    fat100g: 1,
  },
  {
    nameVi: 'bột năng',
    nameEn: 'tapioca starch',
    aliases: ['bot nang', 'tapioca starch'],
    category: 'grain',
    state: 'raw' as const,
    calories100g: 358,
    protein100g: 0.2,
    carbs100g: 88.7,
    fat100g: 0.1,
  },
  {
    nameVi: 'nước lọc',
    nameEn: 'water',
    aliases: ['nuoc loc', 'water'],
    category: 'liquid',
    state: 'unknown' as const,
    calories100g: 0,
    protein100g: 0,
    carbs100g: 0,
    fat100g: 0,
  },
  {
    nameVi: 'kimchi',
    nameEn: 'kimchi',
    aliases: ['kimchi'],
    category: 'vegetable',
    state: 'unknown' as const,
    calories100g: 15,
    protein100g: 1.1,
    carbs100g: 2.4,
    fat100g: 0.5,
  },
];

async function main() {
  for (const food of foods) {
    await db
      .insert(nutritionFoods)
      .values(food)
      .onConflictDoUpdate({
        target: [nutritionFoods.nameVi, nutritionFoods.state],
        set: {
          nameEn: food.nameEn,
          aliases: food.aliases,
          category: food.category,
          calories100g: food.calories100g,
          protein100g: food.protein100g,
          carbs100g: food.carbs100g,
          fat100g: food.fat100g,
          fiber100g: food.fiber100g ?? null,
          sugar100g: food.sugar100g ?? null,
          sodium100g: food.sodium100g ?? null,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`Seeded ${foods.length} nutrition foods.`);
  process.exit(0);
}

main().catch((error) => {
  console.error('Nutrition food seed failed:', error);
  process.exit(1);
});
