export const REPORTING_RPC_GATEWAY = Symbol('REPORTING_RPC_GATEWAY');
export const REPORTING_TCP_CLIENT = Symbol('REPORTING_TCP_CLIENT');
export const REPORTING_SESSION_AUTHENTICATOR = Symbol(
  'REPORTING_SESSION_AUTHENTICATOR',
);
